# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: CI
on:
  push:
    branches:
      - 'feat/github-actions' # TODO: Only for testing purposes. Change to '**' later.

  pull_request:
    branches:
      - 'feat/github-actions' # TODO: Only for testing purposes. Change to '**' later.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Getting the code
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'

      - run: yarn

      - id: file_changes
        name: File Changes
        uses: trilom/file-changes-action@v1.2.3
        with:
          prNumber: $
          pushBefore: ''
          pushAfter: ''

      # TODO: Add more steps for different apps
      - name: Run app-service build
        run: yarn build github-actions-test
        if: contains(steps.file_changes.outputs.files , '"github-actions-test/')

      - name: Run platform-service build
        run: yarn build platform-service
        if: contains(steps.file_changes.outputs.files , '"platform-service/')
