# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: CI
on:
  push:
    branches:
      - '**' # TODO: Only for testing purposes. Change to '**' later.

  pull_request:
    branches:
      - '**' # TODO: Only for testing purposes. Change to '**' later.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Getting the code
        uses: actions/checkout@v3
        with:
          # We need to fetch all branches and commits so that Nx affected has a base to compare against.
          fetch-depth: 0

      - uses: nrwl/nx-set-shas@v2

      - name: Setting up Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Installing dependencies
        run: yarn

      - name: Building affected targets only
        run: yarn nx affected:build --base= origin/main --head=HEAD
